#!/bin/bash

#/opt/hpc/bin/bowtie
bowtie --chunkmbs=400 ${ASSEMBLY}.fa -f -S -t -m1 --best --strata -p4 ${IN}_${LENGTH}_frags | awk -v chr=${IN} '{if (($5 >= 25) && ($3 == chr)) print $3"\t"$4}' | sort -k2,2g > ${IN}_${LENGTH}_bowtie_done

#for size in `cat binsizes`; do
#  /opt/uge/bin/lx-amd64/qsub -V -cwd -l m_mem_free=3G -v LENGTH=$LENGTH -v SIZE=$size -v TYPE=bowtie -v IN=$IN ${GINKGO_PARENT_DIR}ginkgo/genomes/scripts/binBOWTIE
#done
parallel -j ${nproc} env LENGTH=$LENGTH SIZE={} TYPE=bowtie IN=$IN ${GINKGO_PARENT_DIR}ginkgo/genomes/scripts/binBOWTIE :::: binsizes

touch bowtie_done

